### ISSUE TITLE
Plans for 1.19.2?

### ISSUE THREAD

**Issue by mrniddala** [lntricate1/intricarpet#3]
Hello, it would be very nicee if you could update this mod to newer versions:)
Greetings.

**Comment by mrniddala** [comment]
Hello @lntricate1, any info about this please? 😊

**Comment by lntricate1** [comment]
Hello @mrniddala, I might have time to work on updating during next week, I've been busy with school. I can mention you when I get it done if you want.

**Comment by mrniddala** [comment]
Thank you so much<3
