### ISSUE TITLE
Issue with Lithium

### ISSUE THREAD

**Issue by mrniddala** [lntricate1/intricarpet#4]
Hello, here is the crash: https://pastebin.com/raw/pdKQyp7s
I am using the latest Lithium version (0.10.2) on 1.19.2.
Greetings.

**Comment by Pi3tro88** [comment]
same in 1.18.2

**Comment by wendavid552** [comment]
It's caused by overwritting net.minecraft.predicate.entity.EntityPredicates, which could be solved with multiple injecting for the compatibility.

**Comment by wendavid552** [comment]
I try fix the incompatibility issue and gives a snapshot build to it, you could check at [my fork](https://github.com/wendavid552/intricarpet/releases/tag/v1.1.01-alpha.768bf52) here.

**Comment by Pi3tro88** [comment]
> I try fix the incompatibility issue and gives a snapshot build to it, you could check at [my fork](https://github.com/wendavid552/intricarpet/releases/tag/v1.1.01-alpha.768bf52) here.

UwU thankss
